# Generated by Django 2.0.2 on 2018-06-18 01:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_no', models.IntegerField()),
                ('correct_answer', models.TextField()),
                ('incorrect_answers', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Completed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('score', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PlayerProgress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_no', models.IntegerField(default=1)),
                ('score', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_no', models.IntegerField()),
                ('question_text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('category', models.CharField(choices=[('0', 'Any category'), ('9', 'General Knowledge'), ('10', 'Books'), ('11', 'Film'), ('12', 'Music'), ('13', 'Musicals & Theatres'), ('14', 'Television'), ('15', 'Video Games'), ('16', 'Board Games'), ('17', 'Science & Nature'), ('18', 'Computers'), ('19', 'Mathematics'), ('20', 'Mythology'), ('21', 'Sports'), ('22', 'Geography'), ('23', 'History'), ('24', 'Politics'), ('25', 'Art'), ('26', 'Celebrities'), ('27', 'Animals'), ('28', 'Vehicles'), ('29', 'Comics'), ('30', 'Gadgets'), ('31', 'Japanese Anime & Manga'), ('32', 'Cartoon & Animations')], default='0', max_length=2)),
                ('difficulty', models.CharField(choices=[('0', 'Any difficulty'), ('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='0', max_length=6)),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.Tournament'),
        ),
        migrations.AddField(
            model_name='playerprogress',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.Tournament'),
        ),
        migrations.AddField(
            model_name='playerprogress',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='completed',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.Tournament'),
        ),
        migrations.AddField(
            model_name='completed',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.Question'),
        ),
        migrations.AddField(
            model_name='answer',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.Tournament'),
        ),
    ]
